### ISSUE TITLE
addon and menu's work but mount doesn't

### ISSUE THREAD

**Issue by saelfaer** [Friendly0Fire/GW2Addons#1]
showing the menu works, alt+shift+M. setting mount shortcuts exactly like in the gw2 options too
pressing my set shortcut brings the radial menu, hovering over the mounts works as well
but it does not seem to fire the shortcut set in gw2 so the mount does not get selected.

I can however manually use these shortcuts to mount the raptor, skimmer,... indivitually

**Comment by Friendly0Fire** [comment]
Can you tell me what shortcuts you're using for the mounts? Maybe there's a particular keybind that's not handled properly.

**Comment by EbbyEbbs** [comment]
Hello,

I have the same problem, the menu is there (alt+shift+M) and the keybinds for the mounts are like in the GW2 Menu (J+K+L+Ö) but when I press my mount/dismount button, my character mounts _and_ the select menu pops up but changes nothing.
Aside from that, it´s very nice work!

Kind regards

Ebby

**Comment by saelfaer** [comment]
I managed to get it working after 2 restarts and rebinding towards other shortcuts

the ones i used when it didn't work were 
CTRL+ALT+Q
CTRL+ALT+Q
CTRL+ALT+Q

**Comment by EbbyEbbs** [comment]
For me, it´s still not working. Every time I restart the game, the settings in the mount menu vanished. 

I will try to reinstall the addon.

**Comment by Friendly0Fire** [comment]
@EbbyEbbs You'll want to open a separate issue please since it sounds like you're having a different issue.

@saelfaer I'll try with those specific keybinds and see if there's something weird going on.

**Comment by geoeki** [comment]
Jep, same issue here. Removed all bindings for my mounts from my GW2 ingame options and still no luck. Radial menu pops up but I can't use my mounts through it. I did bind the radial menu to Alt, later to N, still the same. Radial menu yes, selection of mount no.

**Comment by geoeki** [comment]
That's btw very likely not bug, people just keep forgetting that they need to set each game keybind for the mounts in the menu, both in the GAME settings AND the addon settings. I had the same issue and was confused because this information is not as clear without the screenshots provided on this git here. Pretty sure that's the case here.

**Comment by saelfaer** [comment]
@geoeki as you can read in my original post I had them bound but they just didn't work with those first keybinds. after rebinding to the other set it started working.

**Comment by Friendly0Fire** [comment]
After review, I cannot reproduce this issue in the current working build.
