### ISSUE TITLE
Using shift to capitalize letters opens the settings panel

### ISSUE THREAD

**Issue by Lunahria** [Friendly0Fire/GW2Addons#10]
I think it just counts it as the shortcut alt + shift + m, depending on how it was coded.
Opening up my chatbox and typing something with capital letters that contains M in it, opens up the settings panel.

**Comment by Friendly0Fire** [comment]
Unless you somehow have Alt held at the same time it shouldn't be possible. The addon specifically looks for the combination of the three keys being held.
