### ISSUE TITLE
using shift in mount hotkeys doesn't work when capslock is on

### ISSUE THREAD

**Issue by saelfaer** [Friendly0Fire/GW2Addons#11]
When using shift in mount hotkeys  for example; my raptor is on  `ALT + SHIFT + O`
behaves different through the radial menu or by pressing that hotkey manually
when caps lock is on.

when caps lock is on, the manual hotkey works, but the radial menu negates the shift and opens the trading post instead (`O` by default)

**Comment by Friendly0Fire** [comment]
Interesting, I'll be sure to look at how caps lock interacts with the key codes.

**Comment by Friendly0Fire** [comment]
I currently cannot reproduce this issue. Caps Lock seems to have no impact on key combinations being sent through to the game.
