### ISSUE TITLE
Using Alt as the menu keybind leaves the radial menu open when Alt+Tab in and out of the game

### ISSUE THREAD

**Issue by geoeki** [Friendly0Fire/GW2Addons#12]
Using Alt as the menu keybind leaves the radial menu open when Alt+Tab in and out of the game. In order to close it, I have to press Alt again when back in the game. _This causes me to unmount however._ Would it be possible to force the menu only to be open when Alt is really pressed? That'd be a huge QoL feature! Great tool, love it otherwise!

**Comment by Friendly0Fire** [comment]
I think I can fix this by listening for the focus loss event (which is sent to the game when alt-tabbing) and cancelling the menu without taking action when that happens.
