### ISSUE TITLE
Menu settings vanish after restart of the game + character mounts before choosing of animal is possible

### ISSUE THREAD

**Issue by EbbyEbbs** [Friendly0Fire/GW2Addons#15]
Hello,

When I start the game, the menu is there (alt+shift+M) and the keybinds for the mounts are like in the GW2 Menu (J+K+L+Ö) but when I press my mount/dismount button, my character mounts instantly without giving me the option to change the mount before. 
When I dismount and press the mount/dismount button while the decay time is still running, I am able to select the mount and my character is mounting the correct animal. 

Furthermore, every time I start the game again, the settings in the menu (alt+shift+M) have completely vanished. 

I will try it again a few times, hope that fixes it (as other people here keep telling).

Ebby

**Comment by Friendly0Fire** [comment]
There's probably two problems at play here:

* For the instant mounting, are you double-binding the ingame mount button with the addon's overlay button? That'll cause this sort of issue.

* For the settings not sticking, that's usually a permission issue. Try running the game as admin, setting your keybinds, then closing and relaunching as normal, the settings should have stuck.

**Comment by EbbyEbbs** [comment]
Your mail got lost in my spam but yes, both problems solved! Thank you, I will enjoy the game now :)
