### ISSUE TITLE
Direct3DCreate9Ex could not be located

### ISSUE THREAD

**Issue by pixel5015** [Friendly0Fire/GW2Addons#17]
When I start up guild wars 2 with this DLL in the bin folder I receive the following error:

The procedure entry point Direct3DCreate9Ex could not be llocated in the dynamic link library \\?\C:\Users\XXXX\XXXXX\AppData\Roaming\Discord\0.0.298\modules\discord_overlay\2\x64\libcef.dll.

I use ARC dps and that works without errors, I tried chainloading it aswell as only having your addon in the bin folder, both gives the same error.

Thank you

**Comment by Friendly0Fire** [comment]
Turn off your Discord overlay as that's what is causing the issue.
