### ISSUE TITLE
Can't Open Menu

### ISSUE THREAD

**Issue by Evodius10** [Friendly0Fire/GW2Addons#18]
i installed the d3d9 dll in my bin 64 and when i do shift +alt+ m it won't show up it just pulls up my map no matter what i do. i've re downloaded the program multiple times and tried to name it for chainloading to see if that would do anything and it didn't. idk what is wrong but i would really like to get a fix to this

**Comment by Bewts** [comment]
I have the exact same problem, shift+alt+m does nothing but open my map.

**Comment by Griifen2473** [comment]
I have the same problem. The key combination doesn't activate the program. I have GW2 installed on a different hard drive. Could that be the problem? If it is, it would be nice to see a fix for this...

**Comment by tycho94** [comment]
I have the same issue, also on a different drive although I wonder if that is the problem. It could also possibly be the keyboard drivers or such.
