### ISSUE TITLE
Quickbar for (Account)Inventory-Slots

### ISSUE THREAD

**Issue by derRAV3N** [Friendly0Fire/GW2Addons#19]
Hey,

I recently had the idea to make an own addon which would just show a few inventory slots anywhere on the screen, which you could just click on and use the referencing item, instead of opening the inventory and then using the item.

Since I saw that you were happy about suggestions, I'm also suggesting this, since I'm totally not sure if I'll be able to do this (on a knowledge/skill level and also because freakin time)

Just suggesting this, feel free to work on it, contacting me or ignore it, I'll have to think and work something out in the coming days/weeks. :)

**Comment by Friendly0Fire** [comment]
This involves reading/modifying game memory which is well beyond the scope of this addon, sorry. It'd also require closing the source and would run afoul of ANet's addon policy.
