### ISSUE TITLE
[feature] Delay showing the overlay

### ISSUE THREAD

**Issue by K900** [Friendly0Fire/GW2Addons#2]
It could be a good UX feature to not show the overlay for a short amount of time after the shortcut is pressed. This allows you to dismount without getting the overlay popup.

**Comment by Friendly0Fire** [comment]
Just to clarify, do you mean having a delay between the moment you press the button and the moment the overlay is displayed such that, if you release the button before the overlay shows up, it just sends whatever was the last mount keybind you used to allow you to dismount/remount without seeing the overlay again?

**Comment by K900** [comment]
Yep. Sorry for the confusing explaination, my brain isn't working right :(

This works already, sort of, because sending any mount keybind while you're on any mount dismounts you, and the griffon is in the middle, but the overlay pops up for a split second and that's kind of annoying. So there's no real need to track what the last keybind was, you can just track the mounted-ness of the player, and then send any random one. Not sure how difficult it is to figure out if the player is mounted though - you definitely can't just count the keypresses because there's a cooldown.

**Comment by Friendly0Fire** [comment]
Yeah, I'll keep track of the last used mount since there are too many variables to take into account to track mounted state. It'd be an option in the config anyway so up to each person as to whether they want a delay and how long they're comfortable with.
