### ISSUE TITLE
Introduced a Keyboard Issue

### ISSUE THREAD

**Issue by asfaraslarry** [Friendly0Fire/GW2Addons#20]
I selected 'V' to pop-up the radial menu.  It used to be what I had bound to mount/dismount (and cleared it, per instructions) so I could use it in the Shift-Alt-M menu (which...only seems to either come up once, or sometimes when you alt-tab back to the game and the keybinding V doesn't seem to be working).

At any rate, what started happening is when the radial menu was operational (I can hit V or click the mouse button bound to V to bring it up), then whenever I hit V in the game, like say, in chat, it would be followed by an E, presumably on key up.

I removed the DLL and restarted the game, bound V back to mount/dismount, and now the error is gone.

Update:  I re-installed it and tried using "Shift-V" to mounting, and now pressing 'V' is fine, but if I press "Shift-V" in chat, sure enough, there is a capital "E" right after it (in the previous instance, it was pressing a lower case 'v' followed by a lower case 'e').  So...what is with that?  :)

**Comment by Friendly0Fire** [comment]
Check your keybinds. The addon does not submit any key that wasn't expressly set by the user, and if you use actual characters as keybinds in the addon's settings, they'll of course be sent to chat since the addon does not attempt (and will never attempt) to learn the game's UI status (e.g. whether chat is in focus).

**Comment by asfaraslarry** [comment]
It's no the keybinds, it's definitely this addon.  I changed the keybind in your app to do "Num -" (something I would never type in chat) and that stopped the 'v' and 'Shift-V' issue, but now if I open chat in the game and hit 'Num -', it is immediately followed by a lower case 'e'.  

Nothing in my keybinds uses 'Num -', I have no keyboard macro application associated with my keyboard (don't think one even exists), much less one that magically follows what I keep changing the bind in this application to so it can add an 'e' on the end.

**Comment by asfaraslarry** [comment]
I have something else I can test, but I need to get into the Shift-Alt-M menu, which is also terribly inconsistent.  It seems like it only works when I can alt-tab back to the game and the radial menu is 'not' working, then Shift-Alt-M works.  Haven't found a way to reliably get it to work, other than removing the DLL, restarting, putting the DLL back, restarting again, then it works during that first session.

**Comment by asfaraslarry** [comment]
Here is what I 'think' is happening.  "ctrl-e" is my setting to open the griffon.  That is the default in your radial menu if you don't move the mouse (I have my "num -" set to the center option, if that matters).  So if I don't activate it from my mouse (which has  button bound to "num -") and just press "num -", it is immediately followed by a "ctrl-e", since the mouse didn't move.  Which, in a chat box, would just be seen as "e".

So your app is working, but it's working 'everywhere', irrespective of whether the UI is up, or could even be up, in the current situation.

I can think of two 'nice to haves' at this point:

1. Do not perform any actions unless the UI is detected/up.
2. Provide a way to move the mouse 'outside' of the UI so 'nothing' is selected, in the event you change your mind and don't want to mount anything after all.

**Comment by Friendly0Fire** [comment]
I've reinvestigated this issue and I'm afraid the only reason this happens is that your mount overlay keybind happens to be a regular character that you'd use in chat.

I cannot detect whether the chat window is in focus or not. I cannot interact with the UI in any way either. These are restrictions set in place by ArenaNet and I intend to respect them, so I'm afraid I cannot solve your issue. You'll need to use a keybind that will not be used in chat.
