### ISSUE TITLE
Using alt+X as mount hotkeys breaks the radial menu on alt-tab

### ISSUE THREAD

**Issue by theRubyUnicorn** [Friendly0Fire/GW2Addons#22]
So I was using Alt+1-4 for my mounts (don't have griffon yet), and every time I alt-tab it breaks the menu, it fixes itself when I open the options menu again with shift alt m.
Probably doesn't recognize that alt has been released afterwards.

**Comment by Friendly0Fire** [comment]
See #12, should be fixed in the next release.
