### ISSUE TITLE
I cannot execute the game when I have the dll in the bin-64 folder

### ISSUE THREAD

**Issue by Neodhoc** [Friendly0Fire/GW2Addons#23]
As mentioned in the title, I have downloaded the files and copied the d3d9.dll to the bin64 folder. After doing that I tried to run the game and I get an error message and the game does not start. Am I doing something wrong? 
The error message is huge but if it is necessary I can copy and paste it here. I would like to note that I don't have any other addons.

The part that reffers to the crash is this one. 
*--> Crash <--*
Assertion: Failed to load Coherent DLL: 0x7e 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(50)
App: Gw2-64.exe 
Pid: 12588
Cmdline: 
BaseAddr: 00007FF77B000000
ProgramId: 101
Build: 85056
When: 2017-12-21T21:34:31Z 2017-12-21T22:34:31+01:00
Uptime:   0 days  0:00:03
Flags: 0

Thanks

**Comment by GoosieBee** [comment]
I am also getting this error now.  Have been using the radial mount for a while so looks like it has to do with an update?

**Comment by FaerSariya** [comment]
Here the same error. Is there any solution yet?

**Comment by Friendly0Fire** [comment]
See the Q&A answer regarding the "Coherent DLL". I can do nothing more for this particular problem, unfortunately.

**Comment by imwithsxc** [comment]
*--> Crash <--*
Assertion: Failed to load file. 
File: ..\..\..\Services\LoadHandle\LoadHandle.cpp(160)
App: Gw2-64.exe 
Pid: 224
Cmdline: -allowInstall
BaseAddr: 00007FF628010000
ProgramId: 101
Build: 90061
When: 2018-06-27T15:06:25Z 2018-06-28T01:06:25+10:00
Uptime:   0 days  0:00:01
Flags: 0
