### ISSUE TITLE
Crash when Capitalizing "O"

### ISSUE THREAD

**Issue by Averieth** [Friendly0Fire/GW2Addons#25]
When I try to type "O" in it's capital form, it crashes.

**Comment by Friendly0Fire** [comment]
I'm going to need more details than this.

**Comment by Averieth** [comment]
What do you need ? It happens every time I type O, non-capital is fine..

**Comment by Friendly0Fire** [comment]
What keybinds did you set in the config? How are you typing "O"? Is there any other letter for which this occurs? Do you have any other addon loaded (e.g. arcdps, ReShade)? What OS are you running?

**Comment by Friendly0Fire** [comment]
I've tried to reproduce this in the current dev build and everything works fine. I'd try to test without TacO or GW2PAO (yes, they can cause crashes too) or any other addon, then re-add just the mounts addon.

If that still doesn't work, the new version should be out shortly. Maybe that'll fix your issue. I'll leave this open for now, but it doesn't sound like it's a problem with this addon right now.

**Comment by Averieth** [comment]
Version 1.0 Fixed the issue, Thanks...
