### ISSUE TITLE
Guild Wars 2 can not start setup 

### ISSUE THREAD

**Issue by imwithsxc** [Friendly0Fire/GW2Addons#27]
--> Crash <--
Assertion: Failed to load file.
File: ......\Services\LoadHandle\LoadHandle.cpp(160)
App: Gw2-64.exe
Pid: 224
Cmdline: -allowInstall
BaseAddr: 00007FF628010000
ProgramId: 101
Build: 90061
When: 2018-06-27T15:06:25Z 2018-06-28T01:06:25+10:00
Uptime: 0 days 0:00:01
Flags: 0

The game was fine until it said I ran out of space so I deleted some games then tried to start it back up but then it began to show an error, so I uninstalled everything and tried to reinstall but it will just pop this error as soon as I open GW2 setup
Pls help

**Comment by Friendly0Fire** [comment]
This doesn't appear to have anything to do with the mounts addon. The installer will never load or use the addon. You should probably ask on the official forums instead.

**Comment by Max16111** [comment]
Yeah my game will crash after this update. When i removed the mount addon file the game is working again fine.

**Comment by Friendly0Fire** [comment]
Make sure you're using the newest version that was just released and if you still get a crash, provide the crash info you can get.

**Comment by Max16111** [comment]
Yeah i downloaded the latest one just 10 mins ago. The game will crash at character select screen . I redownloaded the version before this latest release which i was using and working fine and now the game is working fine. So the issue is with the latest release.

**Comment by Max16111** [comment]
I tried to get the crash report but there no crash report its just when i log on the character select screen its all black and gets stuck and then gw2 will close directly. ANd confirmed the version before this is working fine.

**Comment by asfaraslarry** [comment]
Thank you for all the work!

I just tried this as well, and experience what Max does.  When you get to the character screen, it's black, and some text, boxes for character portraits.  It locks up on loading all the art and such, it looks like, then after a few seconds, it's just gone.

If you put the original DLL back, it works fine again.

**Comment by Friendly0Fire** [comment]
This should now be fixed if you redownload the new release.

**Comment by Max16111** [comment]
Yeah excatly what asfaraslarry said, I wish i can provide you with a report or somethhing to make your life easier but sorry couldnt find one . Anyway will wait for the fix and thanks alot for this beautiful and awesome addon and the work you put into it.

**Comment by Max16111** [comment]
Works like a charm thanks alot :)

**Comment by asfaraslarry** [comment]
I'm able to start the game now and log a character in.  I'll take a look at some of the new options in about 10 minutes or so.  I sadly don't quite have the beetle yet.  13 of the new currency shy.  I should have it tomorrow though.  :)

**Comment by Max16111** [comment]
Whhen you get the beetle it will work just fine just set yr key bindings like what you did with the other mounts. By the way the visuals on this new version is much better keep it up :) GJ cheers

**Comment by Friendly0Fire** [comment]
@imwithsxc Have you managed to get it working?

**Comment by imwithsxc** [comment]
Hi Im not tech saavy and i am lost
i cant even get the setup to work

**Comment by imwithsxc** [comment]
As soon as I press Gw2 setup the message shows so I cant even dl the game at all

**Comment by Friendly0Fire** [comment]
Delete the entire Guild Wars 2 folder in Program Files and download the installer from the website. If you're still having issues, go on the official forums for assistance.

Once the game is installed correctly, you should be able to just follow the readme instructions to reinstall the addon.
