### ISSUE TITLE
Menu opens different mount than the one highlighted

### ISSUE THREAD

**Issue by ChartFish** [Friendly0Fire/GW2Addons#28]
So for example if I'm highlighting the skimmer, I'll hop up on my bunny, if i highlight my bunny, I'll hop up on my raptor. The highlights also don't follow my cursor like it used to in the old version. Basically whichever mount my cursor rests on is the one I mount, but the highlight stays on the one right next to it. It's quite confusing if you don't realize it's happening.

**Comment by Friendly0Fire** [comment]
This is a bug that's been narrowed down to AMD GPUs. I'm looking into it.

**Comment by Friendly0Fire** [comment]
@ChartFish So I appear to be in the strange situation where I personally do not known anyone with an AMD GPU. Would you mind testing [this version](https://github.com/Friendly0Fire/GW2Addons/files/2151151/d3d9.zip) and telling me if it solves the problem?

**Comment by ChartFish** [comment]
It's midnight atm where I am so you'll have to wait untill the morning, but if that's fine I'd be happy to try it out when I wake up.

**Comment by Friendly0Fire** [comment]
Absolutely! Let me know how it turns out.

**Comment by ChartFish** [comment]
same as @loqi93 , still wonky ^^

**Comment by TheDonMeister** [comment]
Can confirm. AMD FX8350 and HD7950 (no laughing! :P) No change from official release sadly.

**Comment by Friendly0Fire** [comment]
Out of curiosity, does this also happen when displaying 4 mounts or 2 mounts? I've noticed a few oddities related to odd/evenness of the number of mounts.

**Comment by SurahCastillo** [comment]
The problem occurs when six or three mounts are shown. In any other case it works properly.

**Comment by TomKriek** [comment]
The problem also occurs with 5 mounts, I did not have the beetle till recently. I will make a small video tonight of the visual bug. Though it seems to be purely visual for me. When I properly hover over the icon of the mount I still mount the correct one it just seems to hightlight the wrong one. But this could be a bit of a different situation than the problem people are having here.

**Comment by andrei9669** [comment]
just a heads up that it's AMD driver issue. 
on 18.8.1 it works correctly but the game has some graphical issues so I reverted back to 18.5.1 now game has no issues but addon has this bug

**Comment by wilecoyote** [comment]
This also happens on my machine with a nvidia geforce gtx 1080 graphics card. So it seems not to be a special AMD issue

**Comment by Friendly0Fire** [comment]
I've tried another minor iteration on the shader (really can't see what's wrong). If someone feels like testing, grab it here: [d3d9.zip](https://github.com/Friendly0Fire/GW2Addons/files/2342790/d3d9.zip).

**Comment by SurahCastillo** [comment]
I just tried that version and it still works badly.
But now it no longer illuminates half sectors (or more than one), now it simply illuminates the next sector (clockwise) that you have marked.

**Comment by Bowch** [comment]
Still picks the wrong mount on my PC: AMD Phenom II X4 955 with an ASUS Strix R9 380X OC.  I've attached a screenshot.

![capture](https://user-images.githubusercontent.com/20127495/44953813-add8f280-ae90-11e8-99cd-79f824e0fd73.PNG)

**Comment by Bowch** [comment]
Same behaviour.

**Comment by loqi93** [comment]
yes, the same problem of the previous build continues

**Comment by wilecoyote** [comment]
In my case the behavior was caused by wrong settings. Gamesetting for the Griffon was 9 on the numeric keypad and should have been 8. But i encounterd another problem. The setting for the favorite mount must be applied each time the game is started or restarted. It seems that the setting for favorite mount is not saved.

**Comment by Friendly0Fire** [comment]
This is really the last thing I can think of: [d3d9.zip](https://github.com/Friendly0Fire/GW2Addons/files/2346641/d3d9.zip)

If that doesn't work, we might have to wait for a new AMD driver...

**Comment by andrei9669** [comment]
@wilecoyote it seems that it has been mentioned but there is no issue made about it [#41](https://github.com/Friendly0Fire/GW2Addons/issues/41#issuecomment-401575257)

**Comment by Bowch** [comment]
If I press Z (my activation key) and hover over a mount in the radial menu, it will highlight the next mount clockwise, but it will actually mount the one that I've hovered over when I let go of Z.

**Comment by Friendly0Fire** [comment]
I'm afraid I don't have any solution for this right now. I don't have AMD hardware to test with.

If someone knows shader programming and has an AMD GPU, I'd greatly appreciate a PR with the fix if you figure it out. Alternatively, if someone has an old AMD GPU (needs to be GCN so it's similar to modern stuff) in the Montreal area that they'd be willing to part with for cheap, please reach out!

**Comment by SurahCastillo** [comment]
I can confirm you that the problem does not only concern to GCN.
On my old 6970 i have the same problem.
