### ISSUE TITLE
Typing Multiple characters in Textboxes

### ISSUE THREAD

**Issue by vanasten1** [Friendly0Fire/GW2Addons#29]
Found a rather annoying bug - when trying to type in the crafting station textboxes, if you press the button that brings up the wheel while also having last mount or favorite mount selected in deadzone, it types both characters in the search bar.

In my instance, having Z set to the racial wheel, and L set to griffon makes it so when I go to type Z, it always types both characters out.

**Comment by asfaraslarry** [comment]
I went through this too, and it's something I think they said can't be fixed, without touching the client in a way that might be frowned upon by ANet.

What is happening is, when you type the character that you have bound to open the radial in chat, it fires off the default (which used to be the griffon) or now, maybe, what is in the dead space (which for me, is still my griffon).  My griffon is bound to 'ctrl-e', so it types an 'e'.

What I did to solve (?) it mostly was to bind the radial to something I'd 'rarely' want to type in chat, and could find another key to type it.  So I went with 'Num -' (minus key on the number pad).  If I really need to type it, I can use the other '-' on the keyboard, and it's something I'd rarely type.

Problem kinda solved.  :)

**Comment by Friendly0Fire** [comment]
Yes, basically I can't "know" that you're currently typing in a text box, so I can't suspend the key from being sent. My best recommendation is to bind the radial menu to a non-alphanumeric key. I personally use Mouse 3 (scroll wheel click) which avoids all of those issues.

I'm afraid I cannot solve this otherwise.

**Comment by vanasten1** [comment]
Fair enough ahah. Il look at setting it to something simpler that wont get typed. Thanks!
