### ISSUE TITLE
Does not work with specific command line arguments

### ISSUE THREAD

**Issue by Silveress** [Friendly0Fire/GW2Addons#30]
Hi there!

If you use shortcuts/manager to log-in to multiple accounts it will not work.

I have narrowed it down to use of -nopatchui -email and -password (they come as a package, cant have one without the others)
As far as I can tell other arguments are not effected.

Not sure if its something ye can fix on yer end :/

**Comment by Friendly0Fire** [comment]
I'll take a look and see if it can be solved, but I can't make promises unfortunately.

**Comment by glaville** [comment]
If you put a copy of the d3d9.dll file in the parent folder (same location that Gw2-64.exe), if will work: Launching the game while disabling the launcher UI makes it work from another directory.

**Comment by Friendly0Fire** [comment]
Well *that* explains a lot. Thanks for the information!
