### ISSUE TITLE
Dead Zone Scale:  If this helps anyone!

### ISSUE THREAD

**Issue by asfaraslarry** [Friendly0Fire/GW2Addons#31]
By default, the new dead zone scale was cranked all the way up for me, and it was confusing to me at first why it seemed like it wasn't working.  What was really happening is the dead zone was so big, I had to drag the cursor really far out to the sides to get it to activate a mount.

I dragged the dead zone down to the middle, and it's perfect.  Barely have to move your mouse around to pick a mount.

Loving the new changes so far, still don''t have my beetle yet, but hopefully in a few hours!  Everything else is going great.  I set my dead zone to open the griffon so it basically works exactly how it used to, and that's my favorite mount anyways.

**Comment by Friendly0Fire** [comment]
The latest hotfixed download has more sane defaults (0.2 instead of 1.0, which is way out of bounds), so that should be good to go now :)
