### ISSUE TITLE
Settings does not appear to actually save favorite mount on disk

### ISSUE THREAD

**Issue by glaville** [Friendly0Fire/GW2Addons#32]
Each time I set a favorite mount in the settings, the choice is kept for the duration of the game, but resets to raptor every time I exit and relaunch GW2.

The "favorite_mount" entry described in the source code is never written in the config file, which explains the problem: could it be a bug in the dumping process (the rest of the options are saved properly) ?

**Comment by HOoD868** [comment]
Yeah, same issue here, it doesnt save the favorite Mount after restarting GW2, would love to see a fix <3

But thanks for updating the Wheel for the new Mount, I have one more suggestions, but will open a new one for it, thanks again.

**Comment by glaville** [comment]
Thank you, your work is really awesome :)
