### ISSUE TITLE
Deadzone as Mountchoice again without having it on the outer Wheel

### ISSUE THREAD

**Issue by HOoD868** [Friendly0Fire/GW2Addons#35]
Man, I can't describe in words how thankful I am for your creation, I play on a Razer Orbweaver and running out on Keys xD - saved my life there.

Now to the suggestion, I REALLY loved to old wheel you made, Griffon in the Middle and the other 4 around it. I am also really glad you updated it for the beetle and find it amazing that you added new functions, but I would love to simplify the radial wheel as much as possible.
Is there a chance you can code it, so the favorite Mount works in the deadzone, without having an own segment on the outer wheel? So basically like the old one just with the beetle added. So fav. Mount (Griffon for me) in the middle, and 1/5 segments for a bigger surface on the outside.

Also, I would love to see a customization option where I can put the mount selection segments where I want them to be.

On a sidenote, if you would open a patreon, I would gladly show you some support to get things like these done.
Thanks, HOoD

**Comment by Friendly0Fire** [comment]
FriendlyFire.6275 :)
