### ISSUE TITLE
White screen at launch

### ISSUE THREAD

**Issue by Lokeri** [Friendly0Fire/GW2Addons#39]
At the lastest build of GW2 and GW2Mount ( 29 June 2018 at 11 pm Paris time ) I have a blank screen when i launch GW2. I have no issue with the version at 01 June 2018. Everything run great.

I run GW2 with ARCDps ONLY as name as "d3d9.dll" everything run great !

I add GW2Mounts as name as "d3d9_chainload.dll", and i have a blank screen when GW2 is launch. And this indefinetly. ( I wait 2 min counter 5s normally and i shutdown GW2 )

I run GW2 with GW2Mounts only as name as "d3d9.dll" and i have a blank screen at the launch.

I tried GW2Mounts name "d3d9.dll" and ArcDPS name "d3d9_mchain.dll" ( as the previous version who works great ) And same thing blank screen.

I attached a DxDiag file if it can help you.

[DxDiag.txt](https://github.com/Friendly0Fire/GW2Addons/files/2151542/DxDiag.txt)

**Comment by Friendly0Fire** [comment]
Juste pour être clair: il n'y a pas de version de GW2Mounts datant du premier juin, donc j'assume que tu veux parler de la version d'octobre 2017 (First Milestone).

Alors, première question: est-ce que tu utilises MSI Afterburner ou similaire? La version actuelle n'est pas compatible avec le RTSS (RivaTuner Statistics Server), donc si ça roule en arrière-plan ça cause toutes sortes de problèmes.

Si c'est pas ça, as-tu essayé de rouler avec GW2Hook (renommé ReShade64.dll)? Je sais que ça peut paraître étrange, mais ça pourrait résoudre le problème, et si tu désactives tous les effets c'est pas mal comme si tu ne l'utilisais pas.

**Comment by Friendly0Fire** [comment]
Duplicate of #36.
