### ISSUE TITLE
gw2mounts, gw2hook and arcdps not working together

### ISSUE THREAD

**Issue by vdurante** [Friendly0Fire/GW2Addons#40]
I renamed arcdps to d3d9_mchain.dll and gw2hook to ReShade64.dll. Both work properly, but gw2mounts stopped working.

**Comment by loqi93** [comment]
yes, working. Only rename with this form:
arcdps: d3d9
mount: d3d9_chainload
hook: ReShade64

**Comment by vdurante** [comment]
@loqi93 idk why it was not working like that either. But I tried once again and now it works! Thank you!
