### ISSUE TITLE
Unsaved settings on mount addon

### ISSUE THREAD

**Issue by Laetys** [Friendly0Fire/GW2Addons#41]
Hi,
After the "Save the Lich" episode, I updated my mount addon to the new look with the beettle, but everytime I disconnect the settings go back to standards, with the beettle not assigned on the panel...

This issue was here as soon as I updated the addon alone. Since then I added arcdps, but there's been no change.

Hope this helps.

**Comment by TheDonMeister** [comment]
Hmmm, My beetle stays assigned, and my deadzone stays correctly set to "favourite mount" But my favourite mount resets from beetle back to raptor if i close and re-launch Guild Wars

**Comment by Friendly0Fire** [comment]
You'll want to try running the game as admin, set your options, then close and re-run normally. The options should've stuck now (except if you set a favorite, that's a bug that'll be fixed in the next release).
