### ISSUE TITLE
Newest version not compatible with GW2Hook

### ISSUE THREAD

**Issue by coolboyjk7** [Friendly0Fire/GW2Addons#42]
Hey there,

The latest version of the addon is not working with GW2Hook for me. I get no error message on screen but the keybind Alt+Shift+M doesn't work anymore. Maybe I've chainloaded things wrong? Here's a complete list of what I run with their names:

-  ArcDPS (d3d9.dll)
-  ArcDPS buildtemplates (d3d9_arcdps_buildtemplates.dll)
-  GW2 Mount addon (d3d9_chainload)
-  GW2Hook chainloader (d3d9_mchain)
-  GW2Hook (ReShade64.dll)

**Comment by loqi93** [comment]
Delete gw2hook chainloader and try

**Comment by Friendly0Fire** [comment]
The FAQ in the readme tells you exactly what you need to load and how to rename each file. The arcdps-provided ReShade chainloader isn't required anymore.
