### ISSUE TITLE
Not working with arcdps/gw2hook

### ISSUE THREAD

**Issue by itslok** [Friendly0Fire/GW2Addons#43]
Its not working with arcdps+gw2hook, i've already done the steps mentioned in the *readme* file. mounts addon doesnt load when i name it to "d3d9_chainload" not does arcdps, and when i name it "d3d9" and arcdps "d3d9_chainload" arcdps does load but not mounts addon. any fix for this ? im on windows 8 and the previous version worked just fine

**Comment by MemeBard** [comment]
I have both working together.
I named Mounts "d3d9.dll" and arc "d3d9_mchain.dll"
hope this helps

**Comment by itslok** [comment]
I've done a clean installation of the game and installed the addons and its working fine now.
