### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by AncaElena10** [Friendly0Fire/GW2Addons#44]
*--> Crash <--*
Assertion: Failed to load Coherent DLL: 0x7e 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(50)
App: Gw2-64.exe 
Pid: 6928
Cmdline: 
BaseAddr: 00007FF673000000
ProgramId: 101
Build: 92121
When: 2018-09-02T22:47:57Z 2018-09-03T01:47:57+03:00
Uptime:   0 days  0:00:04
Flags: 0

*--> System <--*
Name: c430ac72
IpAddr: 192.168.10.107
Processors: 4 [GenuineIntel:6:10:9]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical:  4599MB/ 8090MB  56%
Paged:     5241MB/ 9370MB  55%
Virtual:  134213286MB/134217727MB  3%
Load: 43%
CommitTotal:   4128MB
CommitLimit:   9370MB
CommitPeak:    7862MB
SystemCache:   2925MB
HandleCount:  63863
ProcessCount:   151
ThreadCount:   1826

*--> Process Memory <--*
Private:           90MB
WorkingSet:        93MB
PeakWorkingSet:   197MB
PageFaults:    287967

*--> Memory Category Usage (Inclusive) <--*
[Category]              [Size(MB)]  [Count]     
Root                    70.91       6098        
Uncategorized           38.49       4607        
Programmer Data         25.97       736         
I/O                     25.57       434         
Archive                 24.26       38          
Collide Havok           6.45        755         
Collide                 6.45        755         
File Service            1.24        12          
Collections             0.14        162         
Networking              0.11        14          
Dictionary              0.09        40          
Asset Service           0.07        379         
Event                   0.07        3           
Game                    0.04        55          
Engine                  0.02        12          
Content                 0.02        1           
BTree                   0.02        14          
Threading               0.01        14          
Model-Programmer        0.01        1           
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
UI                      0.00        20          
Text                    0.00        1           

*--> Memory Category Usage (Exclusive) <--*
[Category]              [Size(MB)]  [Count]     
Uncategorized           38.49       4607        
Archive                 24.26       38          
Collide Havok           6.45        755         
File Service            1.24        12          
Networking              0.11        9           
Dictionary              0.09        40          
Asset Service           0.07        379         
Event                   0.07        3           
Collections             0.03        107         
Game                    0.02        45          
Content                 0.02        1           
BTree                   0.02        14          
Threading               0.01        14          
Model-Programmer        0.01        1           
Engine                  0.01        6           
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
Text                    0.00        1           
Download                0.00        3           
UI                      0.00        14          
Programmer Data         0.00        2           
Agent                   0.00        1           
String                  0.00        8           

*--> DllList <--*
C:\Program Files\Guild Wars 2\Gw2-64.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\WS2_32.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\System32\MSASN1.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\System32\PSAPI.DLL
C:\Windows\System32\ole32.dll
C:\Windows\System32\combase.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\windows.storage.dll
C:\Windows\System32\shlwapi.dll
C:\Windows\System32\kernel.appcore.dll
C:\Windows\System32\profapi.dll
C:\Windows\System32\powrprof.dll
C:\Windows\System32\FLTLIB.DLL
C:\Windows\SYSTEM32\MSACM32.dll
C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.17134.228_none_2c308c7e8af52b62\gdiplus.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.17134.228_none_f95000f73097dead\COMCTL32.dll
C:\Windows\SYSTEM32\USP10.dll
C:\Windows\SYSTEM32\MSIMG32.dll
C:\Windows\SYSTEM32\Secur32.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\SSPICLI.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\system32\uxtheme.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\system32\dwmapi.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\mswsock.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\System32\NSI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\System32\winrnr.dll
C:\Windows\System32\wshbth.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\bcrypt.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\System32\TextInputFramework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\system32\explorerframe.dll

*--> Game Context <--*
MapId: 0
Flags: 0x241
ElapsedTime: 00:00:02

*--> World State <--*
<WorldState />

[DbgHelp.dll is C:\Windows\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 10.0.17134.1 (64/32-bit compatible)]

*--> ClientContextThreadProc Thread 0x2a28 <--*

*--> Trace <--*
Pc                Rt                : Args
00007ff6`731c443c 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`731c44bb 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`73c50622 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`7360679d 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`73604ced 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`735309fb 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`7352f502 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`731a3b47 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`73392cce 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`73390e3e 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`73390ab9 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`7339221f 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`733904bc 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`731bb2a1 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`73349839 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffc`cf323034 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffc`d1e11431 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 

*--> Thread registers <--*
rax=0000000000000001 rbx=00007ff6746c4448 rcx=000000934bafe5b0
rdx=00007ff6746c4448 rsi=0000000000000032 rdi=000000934bafeae0
rip=00007ff6731c43dd rsp=000000934bafe550 rbp=000000934bafee60
 r8=0000000000000032  r9=00007ff673000000 r10=000000934bafe7d6
r11=000000934bafea10 r12=0000000000000002 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000202

rbx-32 00007FF6746C4428  62655761`6e657241 6e657265`686f435c 74477741`5c744774 00000000`7070632e 
rbx +0 00007FF6746C4448  2e2e5c2e`2e5c2e2e 5c656e69`676e455c 62655761`6e657241 6e657265`686f435c 
rbx+32 00007FF6746C4468  6f437741`5c695574 00000070`70632e68 73676e69`74746573 6d616e65`6c69662e 
rcx-32 000000934BAFE590  00007ff6`731c43dd 00000093`4bafe550 00000093`4bafee60 00000007`00000021 
rcx +0 000000934BAFE5B0  00000000`00000020 00000000`ffffffff 0000023e`00000000 00000093`4bafe7d6 
rcx+32 000000934BAFE5D0  00000200`00000002 00000000`00000000 00009f80`0010000f 0053002b`002b0033 
rdx-32 00007FF6746C4428  62655761`6e657241 6e657265`686f435c 74477741`5c744774 00000000`7070632e 
rdx +0 00007FF6746C4448  2e2e5c2e`2e5c2e2e 5c656e69`676e455c 62655761`6e657241 6e657265`686f435c 
rdx+32 00007FF6746C4468  6f437741`5c695574 00000070`70632e68 73676e69`74746573 6d616e65`6c69662e 
 r9 +0 00007FF673000000  00000003`00905a4d 0000ffff`00000004 00000000`000000b8 00000000`00000040 
 r9+32 00007FF673000020  00000000`00000000 00000000`00000000 00000000`00000000 00000168`00000000 

*--> Code <--*
00007ff6`731c43bd  488bf941 8bf0488d 0d56efb5 01488bda H..A..H..V...H..
00007ff6`731c43cd  e8fe7dfe ff488d4c 2460ff15 5bef2b01 ..}..H.L$`..[.+.
00007ff6`731c43dd  488b8424 58010000 4c8d0534 682d0148 H..$X...L..4h-.H
00007ff6`731c43ed  89442440 4885db48 8b8424f8 00000044 .D$@H..H..$....D
00007ff6`731c43fd  8bce4889 4424484c 0f45c348 8b842400 ..H.D$HL.E.H..$.
00007ff6`731c440d  01000048 8bd74889 44245033 c9488d44 ...H..H.D$P3.H.D

*--> Stack <--*
00000093`4bafe550  00000093`4bafeb01 00000000`00000200 00000000`00000021 00000000`00000000 ...K............!...............
00000093`4bafe570  00000093`4bafe590 00000093`4bafe5b0 00000000`00000000 00000093`4bafe538 ...K.......K............8..K....
00000093`4bafe590  00007ff6`731c43dd 00000093`4bafe550 00000093`4bafee60 00000007`00000021 .C.s....P..K....`..K....!.......
00000093`4bafe5b0  00000000`00000020 00000000`ffffffff 0000023e`00000000 00000093`4bafe7d6  ...................>......K....
00000093`4bafe5d0  00000200`00000002 00000000`00000000 00009f80`0010000f 0053002b`002b0033 ........................3.+.+.S.
00000093`4bafe5f0  00000202`002b002b 00007ffc`a1728654 00000000`00000000 00007ffc`a16300f8 +.+.....T.r...............c.....
00000093`4bafe610  00000000`00000040 00000000`00000000 0000023e`5e874080 00000000`00000001 @................@.^>...........
00000093`4bafe630  00000093`4bafe5b0 00007ff6`746c4448 00007ff6`746c4448 00000093`4bafe550 ...K....HDlt....HDlt....P..K....
00000093`4bafe650  00000093`4bafee60 00000000`00000032 00000093`4bafeae0 00000000`00000032 `..K....2..........K....2.......
00000093`4bafe670  00007ff6`73000000 00000093`4bafe7d6 00000093`4bafea10 00000000`00000002 ...s.......K.......K............
00000093`4bafe690  00000000`00000000 00000000`00000000 00000000`00000000 00007ff6`731c43dd .........................C.s....
00000093`4bafe6b0  00000000`0000027f 00000000`00000000 00000000`00000000 0000ffff`00009f80 ................................
00000093`4bafe6d0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe6f0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe710  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe730  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe750  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe770  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe790  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe7b0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe7d0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe7f0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe810  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe830  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000093`4bafe850  00000000`00000600 0000023e`5ea3e9e0 0000023e`5ea39d60 00007ffc`d1db0428 ...........^>...`..^>...(.......
00000093`4bafe870  0000023e`5ea3e560 00007ffc`d1dbea16 00000000`00000000 00000093`4bafebd0 `..^>......................K....
00000093`4bafe890  00000000`00000004 00007ffc`d1db0428 00000000`00000600 00000000`00000000 ........(.......................
00000093`4bafe8b0  0000023e`5ea1f110 00007ffc`d1e2137c 0000023e`5ea39fd8 00000000`00000000 ...^>...|..........^>...........
00000093`4bafe8d0  00000000`00000000 00000093`4bafebd0 0000023e`5ea3e090 0000023e`5ea3e560 ...........K.......^>...`..^>...
00000093`4bafe8f0  00000000`00000600 00000000`00000000 00000000`00000000 00000093`4bafebd0 ...........................K....
00000093`4bafe910  00000000`00000000 00000000`5ea30101 00000000`000003a8 00000000`00000075 ...........^............u.......
00000093`4bafe930  0000023e`5eb139f0 00007ffc`d1de05b4 00000093`00c4ec00 00000000`00000075 .9.^>...................u.......

well.. :(

**Comment by Friendly0Fire** [comment]
Quoting the FAQ:

### Q: I'm having a crash on launch mentioning "Coherent DLL", what do?

A: There seems to be a lot of potential reasons for this particular crash. [BGDM's website](http://gw2bgdm.blogspot.com/p/faq.html#2.5) lists quite a few. I'd especially recommend making sure you have the very latest [VC++ Redist](https://go.microsoft.com/fwlink/?LinkId=746572).

**Comment by AncaElena10** [comment]
Thank you for that site, c. (D3DX9_43.DLL ) helped me,
