### ISSUE TITLE
GW2Mounts folder and config file not being created

### ISSUE THREAD

**Issue by MMRizy** [Friendly0Fire/GW2Addons#46]
GW2Mounts folder is not being created in addons folder inside main GW2 folder, and config file is not automatically created/saving so every time i re-log I have to set up all the keybindings again...

**Comment by Friendly0Fire** [comment]
Yes, this is the only solution. Unfortunately, ArenaNet requires addon developers to put the settings files in that folder, which goes against Microsoft's best practices and therefore is often blocked by the OS for security reasons.
