### ISSUE TITLE
Crashing to Desktop with latest version of GW2

### ISSUE THREAD

**Issue by Solarswordsman** [Friendly0Fire/GW2Addons#48]
**Describe the bug**
After 5-15 minutes of play, the game crashes to desktop.

**To Reproduce**
1. Install the mod as usual
2. Play for a bit (I was hitting things, I didn't even use the mount menu)
3. Crash to Desktop, no error.

**Expected behavior**
Not crashing to desktop

**Screenshots**
My wallpaper is boring :)

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: GTX 1070 (latest nvidia drivers)
 - Was chainloading with arcdps's built-in chainloader, then removed arcdps to only use this (I'd rather have this).  Neither configuration worked.

**Additional context**
N/A

**Comment by Friendly0Fire** [comment]
So I'm looking into these new build issues, but thus far I haven't had a crash using the latest dev build. Mind trying with that? Here it is: [d3d9.zip](https://github.com/Friendly0Fire/GW2Addons/files/2444631/d3d9.zip)
