### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by Icaryu** [Friendly0Fire/GW2Addons#52]
**Describe the bug**
I have a bug with the display of the addon. You can see what the radial thing do on the screenshots for all mounts.

**To Reproduce**
I just press the shortcut I have to display the radial thing, and the radial thing shows up and when I want to select a mount, the selection of it doesn't work exactly like it's supposed to be.

**Expected behavior**
Well, when I select a mount with my cursor, I expect that the "light" will be on the selected mount.

**Screenshots**
![gw013](https://user-images.githubusercontent.com/44555732/47621759-bbab9c80-dafc-11e8-849c-8ffb86734437.jpg)
![gw014](https://user-images.githubusercontent.com/44555732/47621760-bc443300-dafc-11e8-899e-6ebd05e710d1.jpg)
![gw015](https://user-images.githubusercontent.com/44555732/47621761-bc443300-dafc-11e8-990a-94e200109c4d.jpg)
![gw016](https://user-images.githubusercontent.com/44555732/47621762-bc443300-dafc-11e8-88ef-e61cf8c44ca5.jpg)
![gw017](https://user-images.githubusercontent.com/44555732/47621763-bc443300-dafc-11e8-875e-441828501b5e.jpg)
![gw011](https://user-images.githubusercontent.com/44555732/47621764-bc443300-dafc-11e8-99e4-7023b6b7366a.jpg)
![gw012](https://user-images.githubusercontent.com/44555732/47621765-bcdcc980-dafc-11e8-8ad6-053b943cb47d.jpg)

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: _maybe "Radeon 530", but I'm not really sure about it_
 - Chainloading : arcdps

**Additional context**
I did already some tests, and if I delete arcdps, the problem is still the same. I even changed my shortcuts, and I have twice uninstalled and installed it again, and it didn't work as well... I agree that this is not a big problem, but it's still confusing when you don't have the mount you highlighted ^^
Finally, I'm french, so I'm sorry for my bad english...

**Comment by loqi93** [comment]
That problem has already been solved and we are waiting for developer to launch a new update to fix it.

**Comment by Icaryu** [comment]
Oh ok, thank you ! 😊😊😊
