### ISSUE TITLE
Options menu doesnt take in any keybind input

### ISSUE THREAD

**Issue by bo6aga** [Friendly0Fire/GW2Addons#56]
**Describe the bug**
Hi, so earlier i downloaded the addon tried to set my key bindings into the options menu, but the the menu would take in any inputs. Wouldn't matter what button I tried to set as a keybind, the keybind will not appear.

**To Reproduce**
1. Launch GW2.
2. Open the options menu, try to set keybinds

**Expected behavior**
The button I press should be taken in as a keybind. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12594751/48894308-76f0f800-ee53-11e8-9492-6b8b40e0d5b8.png)

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: GTX 970
 - Chainloading: None

**Additional context**

**Comment by Friendly0Fire** [comment]
Just to be clear:
* Can you interact with the menu at all? Tick a checkbox, slide a slider, just something that shows the UI's getting input.
* Assuming it *does* respond to input: when you try to set a keybind, are you first pressing Set, then holding your keybind and releasing?
