### ISSUE TITLE
Game doesn't load correctly

### ISSUE THREAD

**Issue by zeezorro** [Friendly0Fire/GW2Addons#57]
**Describe the bug**
I launch the game and guild war's has a habit of going white with a black bottom every time i start the game. However, the character menu comes up for me to select the character. Once i installed the d3d9.lll it stayed like this indefinitely even though the audio clearly tells me the game is launched and running.

**To Reproduce**
1. Download, extract, and install the most current version into the guild wars 2 bin64 folder'...'
2. Launch the game in windowed full screen  '...'
3. Game go's white with black bar at the bottom and stay's that way

**Expected behavior**
Expected:
![image](https://user-images.githubusercontent.com/45445340/49198312-8515ab80-f360-11e8-9052-b83740116e25.png)

This being normal character screen loaded.

**Screenshots**

![image](https://user-images.githubusercontent.com/45445340/49198270-467ff100-f360-11e8-9e1f-244f292c39ea.png)

This being what i get when i have the d3d9.dll in my bin64 folder

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: GTX1080
 - Chainloading, if any [e.g. arcdps -> GW2Mounts -> GW2Hook]

**Additional context**
In the task manager, Guild war's 2 stop's responding as it's launched. I attempted to play in full screen and in fullscreen windowed, both ended with the game not launching properly.

**Comment by Friendly0Fire** [comment]
The only possible thing I can think of would be: do you have RivaTuner Statistics Server running? It's installed with stuff like Afterburner to monitor overclocks and framerates. It seems to very much dislike the addon.

**Comment by zeezorro** [comment]
I do have Riva statisctics running. I'll try stopping it and starting it again

**Comment by zeezorro** [comment]
As it turn's out, Riva was the problem. Thank you!
