### ISSUE TITLE
The Hotkey doesn't work 

### ISSUE THREAD

**Issue by GalaxySceen** [Friendly0Fire/GW2Addons#58]
**Describe the bug**
The Hotkey Shift+Alt+M just opens my map, I installed the latest version of GW2 Mounts, d3d9.dll into the bin64 file of the GW2 downloaded directory, also, if I don't change the name of d3d9.dll into d3d9 (Mounts).dll I can't even get into the game (It crashes). I even reinstalled GW2 just to check if something is not right with it.

**To Reproduce**
1. Downloading and extracting d3d9.dll into the bin64 file of GW2 
2. Run the Game
3. Crash / Opens map (the hotkey doesn't work)

**Expected behavior**
 To run 

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: Intel HD graphics 630 (I7-7700k)
 - No chainloading whatsoever

**Comment by Friendly0Fire** [comment]
Renaming the addon to be anything but `d3d9.dll` means it'll never be loaded (unless you chainload it, and even then only certain names work), so that explains that.

Now, as to why it crashes. The very first step here is gonna be to see what the event viewer has to say, so follow these steps:
1. Run the game with the addon named `d3d9.dll` and get a crash to occur.
2. Follow these steps to get to the event viewer in the right category: https://communities.bentley.com/products/electrical___instrumentation/w/electrical_and_instrumentation__wiki/33310/diagnose-a-program-crash-using-event-viewer
3. Look through Errors for a crash from the game, `Gw2-64.exe`.
4. Copy the entire text box at the bottom with a bunch of information and paste it here as an answer.

Hopefully we can get some info from there.

**Comment by GalaxySceen** [comment]
*--> Crash <--*
Assertion: Failed to load Coherent DLL: 0x7e 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(50)
App: Gw2-64.exe 
Pid: 56912
Cmdline: 
BaseAddr: 00007FF79C080000
ProgramId: 101
Build: 93877
When: 2018-11-30T07:01:55Z 2018-11-30T09:01:55+02:00
Uptime:   0 days  0:00:01
Flags: 0

*--> System <--*
Name: 30e849be
IpAddr: 192.168.0.213
Processors: 8 [GenuineIntel:6:14:9]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical: 10663MB/16274MB  65%
Paged:    12116MB/18706MB  64%
Virtual:  134213161MB/134217727MB  3%
Load: 34%
CommitTotal:   6590MB
CommitLimit:  18706MB
CommitPeak:   13175MB
SystemCache:   5159MB
HandleCount:  68955
ProcessCount:   147
ThreadCount:   6104

*--> Process Memory <--*
Private:           96MB
WorkingSet:        94MB
PeakWorkingSet:   199MB
PageFaults:    191486

*--> Memory Category Usage (Inclusive) <--*
[Category]              [Size(MB)]  [Count]     
Root                    71.89       6060        
Uncategorized           39.00       4618        
Programmer Data         26.44       687         
I/O                     26.06       442         
Archive                 24.75       38          
Collide                 6.45        755         
Collide Havok           6.45        755         
File Service            1.24        12          
Collections             0.12        105         
Networking              0.11        14          
Dictionary              0.09        41          
Asset Service           0.07        387         
Event                   0.07        3           
Game                    0.04        55          
Engine                  0.02        12          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
BTree                   0.01        12          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
UI                      0.00        20          
Text                    0.00        1           

*--> Memory Category Usage (Exclusive) <--*
[Category]              [Size(MB)]  [Count]     
Uncategorized           39.00       4618        
Archive                 24.75       38          
Collide Havok           6.45        755         
File Service            1.24        12          
Networking              0.11        9           
Dictionary              0.09        41          
Asset Service           0.07        387         
Event                   0.07        3           
Game                    0.02        45          
Content                 0.02        1           
Threading               0.01        14          
Collections             0.01        51          
Model-Programmer        0.01        1           
BTree                   0.01        12          
Engine                  0.01        6           
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
Text                    0.00        1           
Download                0.00        3           
UI                      0.00        14          
Programmer Data         0.00        2           
Agent                   0.00        1           
String                  0.00        8           

*--> DllList <--*
C:\Program Files\Guild Wars 2\Gw2-64.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\WS2_32.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\System32\MSASN1.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\System32\PSAPI.DLL
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\windows.storage.dll
C:\WINDOWS\System32\shlwapi.dll
C:\WINDOWS\System32\kernel.appcore.dll
C:\WINDOWS\System32\profapi.dll
C:\WINDOWS\System32\powrprof.dll
C:\WINDOWS\System32\FLTLIB.DLL
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.17134.407_none_2c2f90488af60bb7\gdiplus.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.17134.407_none_f94e16e330999300\COMCTL32.dll
C:\WINDOWS\SYSTEM32\USP10.dll
C:\WINDOWS\SYSTEM32\MSIMG32.dll
C:\WINDOWS\SYSTEM32\Secur32.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\SSPICLI.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\system32\uxtheme.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\system32\dwmapi.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\mswsock.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\TextInputFramework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\WINDOWS\system32\explorerframe.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\bcrypt.dll
C:\Windows\System32\rasadhlp.dll

*--> Game Context <--*
MapId: 0
Flags: 0x241
ElapsedTime: 00:00:01

*--> World State <--*
<WorldState />

[DbgHelp.dll is C:\WINDOWS\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 6.2.17134.1 (64/32-bit compatible)]

*--> ClientContextThreadProc Thread 0xd0e4 <--*

*--> Trace <--*
Pc                Rt                : Args
00007ff7`9c24b14c 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c24b1cb 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9cceae52 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c694e1d 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c693367 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c5ba26b 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c5b8d72 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c229107 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c419aee 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c417d2e 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c4179a9 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c41903f 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c4173ac 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c241e91 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`9c3d0819 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff8`e1f93034 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff8`e41b1471 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 

*--> Thread registers <--*
rax=0000000000000001 rbx=00007ff79d812cb8 rcx=0000003432afe5a0
rdx=00007ff79d812cb8 rsi=0000000000000032 rdi=0000003432afead0
rip=00007ff79c24b0ed rsp=0000003432afe540 rbp=0000003432afee50
 r8=0000000000000032  r9=00007ff79c080000 r10=0000003432afe7c6
r11=0000003432afea00 r12=0000000000000002 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000202

rbx-32 00007FF79D812C98  62655761`6e657241 6e657265`686f435c 74477741`5c744774 00000000`7070632e 
rbx +0 00007FF79D812CB8  2e2e5c2e`2e5c2e2e 5c656e69`676e455c 62655761`6e657241 6e657265`686f435c 
rbx+32 00007FF79D812CD8  6f437741`5c695574 00000070`70632e68 73676e69`74746573 6d616e65`6c69662e 
rcx-32 0000003432AFE580  00007ff7`9c24b0ed 00000034`32afe540 00000034`32afee50 00000007`00000021 
rcx +0 0000003432AFE5A0  00000000`00000020 00000000`ffffffff 000001b3`9f5d0000 00000034`32afe7c6 
rcx+32 0000003432AFE5C0  00000000`00000002 00000034`32afe6a4 00009f80`0010000f 0053002b`002b0033 
rdx-32 00007FF79D812C98  62655761`6e657241 6e657265`686f435c 74477741`5c744774 00000000`7070632e 
rdx +0 00007FF79D812CB8  2e2e5c2e`2e5c2e2e 5c656e69`676e455c 62655761`6e657241 6e657265`686f435c 
rdx+32 00007FF79D812CD8  6f437741`5c695574 00000070`70632e68 73676e69`74746573 6d616e65`6c69662e 
 r9 +0 00007FF79C080000  00000003`00905a4d 0000ffff`00000004 00000000`000000b8 00000000`00000040 
 r9+32 00007FF79C080020  00000000`00000000 00000000`00000000 00000000`00000000 00000168`00000000 

*--> Code <--*
00007ff7`9c24b0cd  488bf941 8bf0488d 0dc6c8c6 01488bda H..A..H......H..
00007ff7`9c24b0dd  e88e77fe ff488d4c 2460ff15 4b323801 ..w..H.L$`..K28.
00007ff7`9c24b0ed  488b8424 58010000 4c8d0564 b7390148 H..$X...L..d.9.H
00007ff7`9c24b0fd  89442440 4885db48 8b8424f8 00000044 .D$@H..H..$....D
00007ff7`9c24b10d  8bce4889 4424484c 0f45c348 8b842400 ..H.D$HL.E.H..$.
00007ff7`9c24b11d  01000048 8bd74889 44245033 c9488d44 ...H..H.D$P3.H.D

*--> Stack <--*
00000034`32afe540  00000034`32afeaf1 00000000`00000200 00000000`00000021 00000000`00000000 ...24...........!...............
00000034`32afe560  00000034`32afe580 00000034`32afe5a0 00000000`00000000 00000034`32afe528 ...24......24...........(..24...
00000034`32afe580  00007ff7`9c24b0ed 00000034`32afe540 00000034`32afee50 00000007`00000021 ..$.....@..24...P..24...!.......
00000034`32afe5a0  00000000`00000020 00000000`ffffffff 000001b3`9f5d0000 00000034`32afe7c6  .................]........24...
00000034`32afe5c0  00000000`00000002 00000034`32afe6a4 00009f80`0010000f 0053002b`002b0033 ...........24...........3.+.+.S.
00000034`32afe5e0  00000202`002b002b 00000000`00000000 00000034`32afe6e0 00000000`00000840 +.+................24...@.......
00000034`32afe600  0000f9eb`d05db0a6 00007ff8`e417ab5c 00000034`32afebd0 00000000`00000001 ..].....\..........24...........
00000034`32afe620  00000034`32afe5a0 00007ff7`9d812cb8 00007ff7`9d812cb8 00000034`32afe540 ...24....,.......,......@..24...
00000034`32afe640  00000034`32afee50 00000000`00000032 00000034`32afead0 00000000`00000032 P..24...2..........24...2.......
00000034`32afe660  00007ff7`9c080000 00000034`32afe7c6 00000034`32afea00 00000000`00000002 ...........24......24...........
00000034`32afe680  00000000`00000000 00000000`00000000 00000000`00000000 00007ff7`9c24b0ed ..........................$.....
00000034`32afe6a0  00000000`0000027f 00000000`00000000 00000000`00000000 0000ffff`00009f80 ................................
00000034`32afe6c0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe6e0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe700  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe720  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe740  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe760  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe780  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe7a0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe7c0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe7e0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe800  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe820  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000034`32afe840  00000000`00000600 000001b3`9f5d6b80 000001b3`a71c34f0 00007ff8`e4150428 .........k]......4......(.......
00000034`32afe860  000001b3`9f5d71e0 00007ff8`e415ea16 00000000`00000000 00000034`32afebc0 .q]........................24...
00000034`32afe880  00000000`00000004 00007ff8`e4150428 00000000`00000600 00000000`00000000 ........(.......................
00000034`32afe8a0  000001b3`9f578670 00007ff8`e41c13bc 000001b3`a71c3768 00000000`00000000 p.W.............h7..............
00000034`32afe8c0  00000000`00000000 00000034`32afebc0 000001b3`9f5d67d0 000001b3`9f5d71e0 ...........24....g]......q].....
00000034`32afe8e0  00000000`00000600 00000000`00000000 00000000`00000000 00000034`32afebc0 ...........................24...
00000034`32afe900  00000000`00000000 00000000`9f5d0101 00000000`00000168 00000000`0000002d ..........].....h.......-.......
00000034`32afe920  000001b3`a71c7230 00007ff8`e41805f4 00000034`003cec00 00000000`0000002d 0r................<.4...-.......

(that's the log of the Gw2-64.exe)
Though in my Event Viewer it seems there is not getting any errors by crash, only the gw2 client 
This is only the crash report from the actual game

**Comment by Friendly0Fire** [comment]
Can you check [this](https://github.com/Friendly0Fire/GW2Addons#q-im-having-a-crash-on-launch-mentioning-coherent-dll-what-do) entry in the FAQ and follow all of the instructions?
