### ISSUE TITLE
First time using this addon and SHIFT+ALT+M doesn't open the menu...

### ISSUE THREAD

**Issue by Coding-Cyanide** [Friendly0Fire/GW2Addons#61]
First time using this addon and SHIFT+ALT+M doesn't open the menu, I have the .dll installed in the bin64 directory of guild wars 2 (It opened map when I had it enabled but I no longer do because I use a different map key)

Specs:
OS: Windows 10
GPU: GTX 1050 TI

**Comment by Coding-Cyanide** [comment]
No
Yes
No
No

Sorry for the short response, been busy today, Thank you for the response!
~Cyanide

**Comment by Friendly0Fire** [comment]
Hmm... A few more questions then:

* Do you use the GW2 command line arguments `-nopatchui`, `-email` and `-password`? If so, you need to place the DLL one level up, next to `Gw2-64.exe`.
* What language is your OS in?

**Comment by Coding-Cyanide** [comment]
I don't believe so
English (US)

**Comment by KalSpiro** [comment]
I was having the same issue, I use all of those arguments.  Moving it up a step fixed it, so Thanks.  Hopefully C-C can get it working too
