### ISSUE TITLE
GW2 does not initialize with addon installed

### ISSUE THREAD

**Issue by deadpyxel** [Friendly0Fire/GW2Addons#65]
**Describe the bug**
If I keep the addon installed, GW2 does not initialize/launch

**To Reproduce**
1. Install the addon in bin64 folder
2. Try to launch the game
3. During the initialization phase, GW2 crashes and dies.

**Expected behavior**
Game should load normally, given that the steps are the usual installation

**Screenshots**
[Post crash screenshot.](https://i.imgur.com/BMqOovB.png)

**System configuration (please fill in):**
 - OS: Windows 10 x64
 - GPU: No GPU, Intel HD Graphics
 - Chainloading: None, but I tried chainloading with arcdps, and same ocurred.

**Additional context**
I also tried to load only ArcDPS, but the same kind of crash ocurred, so I am suspecting there's some kind of campatibility problem, but I am not sure how to debug it. Let me know if there's any steps I can go trough to test it. Also, right now I am running a repair of my installation, if that works I'll let you know.

**EDIT:** Trying to repair or reinstall did not work. I am leaning towards compatibility issues.

**Comment by Friendly0Fire** [comment]
Check if the new version fixes it.

**Comment by deadpyxel** [comment]
I worked for me, but I had to reinstall Visual C++ Redistribute and DirectX. I think this is a local bug.

**Comment by Friendly0Fire** [comment]
Awesome, thanks for the update.
