### ISSUE TITLE
GW2mounts go conflict with discord

### ISSUE THREAD

**Issue by Andri89** [Friendly0Fire/GW2Addons#9]
Hello since I installed this addon if I open discord with guild wars 2, the latter causes the game crash. Why am I writing here? It is very simple, if I delete Gw2Mounts, the game will normally also run with discord and vice versa. Can you help me?

**Comment by Andri89** [comment]
ok seems to have been resolved by disabling the overlay of discord, maybe it is better that you still control the right thing for the spirit of completeness, good giveaway though thank you so much.

**Comment by Friendly0Fire** [comment]
I'm afraid I can't control what Discord does with their own overlay, so it'd be difficult for me to pinpoint what they're doing that'd crash this.
